# ===== SQL Server Configuration =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TEST;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=chickhenR2#
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=none

# ===== SQL Init =====
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.format_sql=true

# ===== Server =====
server.port=8383

# ===== Swagger / OpenAPI =====
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===== hazelcast =====
hazelcast.cluster-name=${HAZELCAST_CLUSTER_NAME:dev}
hazelcast.address=${HAZELCAST_ADDRESS:localhost:5701}
